/*
	tps23
	
	Data Generator for Social@Panther
	
	User information generated by Random User Generator (https://randomuser.me/)
	Thank you, Random User Generator =)
*/

"use strict";

var DATA_GENERATOR;

$(document).ready(function() {
	var randomUserAPI = 'https://randomuser.me/api/',
		userCount = 100,
		visualOutput = $("#output")[0];
	
	function DataGenerator() {
		this.users;
		
		this.generateData();
		
		return;
	}
	
	DataGenerator.prototype.generateData = function() {
		this.getUsers();
		
		return;
	}
	
	DataGenerator.prototype.getUsers = function() {
		$.ajax({
			url: randomUserAPI + '?results=' + userCount,
			dataType: 'json',
			success: function(result, status, xhr) {
				DATA_GENERATOR.users = result.results;
				console.log(DATA_GENERATOR.users);
				
				DATA_GENERATOR.createSQL();
				
				return;
			}
		});
		
		return;
	}
	
	function appendBR() {
		return visualOutput.append(document.createElement("br"));
	}
	
	DataGenerator.prototype.createSQL = function() {
		var i,
			div = document.createElement("div");
		
		div.innerHTML = "<strong>--INSERT USERS:</strong>";
		visualOutput.append(div);
		for(i = 0; i < this.users.length; i++) {
			div = document.createElement("div");
			div.innerHTML = "<span>INSERT INTO PROFILE (name, email, password, date_of_birth) VALUES (" +
				"'" + this.users[i].name.title + ' ' + this.users[i].name.first + ' ' + this.users[i].name.last + "'," +
				"'" + this.users[i].email + "'," +
				"'" + this.users[i].login.password + "'," +
				"'" + this.users[i].dob + "');</span>";
			visualOutput.append(div);
		}
		appendBR();
		
		
		div.innerHTML = "<strong>--INSERT FRIENDSHIPS:</strong>";
		visualOutput.append(div);
		for(i = 0; i < this.users.length; i++) {
			div = document.createElement("div");
			div.innerHTML = "<span>INSERT INTO FRIENDS (userID1, userID2, JDate, message) VALUES (" +
				"'" + this.users[i].name.title + ' ' + this.users[i].name.first + ' ' + this.users[i].name.last + "'," +
				"'" + this.users[i].email + "'," +
				"'" + this.users[i].dob + "');</span>";
			visualOutput.append(div);
		}
		appendBR();
		
		
		div.innerHTML = "<strong>--INSERT GROUPS:</strong>";
		visualOutput.append(div);
		for(i = 0; i < this.users.length; i++) {
			div = document.createElement("div");
			div.innerHTML = "<span>INSERT INTO GROUPS (gID, name, description) VALUES (" +
				"'" + this.users[i].name.title + ' ' + this.users[i].name.first + ' ' + this.users[i].name.last + "'," +
				"'" + this.users[i].email + "'," +
				"'" + this.users[i].dob + "');</span>";
			visualOutput.append(div);
		}
		appendBR();
		
		
		div.innerHTML = "<strong>--INSERT MESSAGES:</strong>";
		visualOutput.append(div);
		for(i = 0; i < this.users.length; i++) {
			div = document.createElement("div");
			div.innerHTML = "<span>INSERT INTO MESSAGES (msgID, fromID, message, toUserID, toGroupID, dateSent) VALUES (" +
				"'" + this.users[i].name.title + ' ' + this.users[i].name.first + ' ' + this.users[i].name.last + "'," +
				"'" + this.users[i].email + "'," +
				"'" + this.users[i].registered + "');</span>";
			visualOutput.append(div);
		}
		appendBR();
		
		
		return;
	}
	
	DATA_GENERATOR = new DataGenerator();
	
	return;
});
