--Social@Panther
--Terence Sperringer (tps23)
--Sizhe Sun (sis61)

--Generated Data for Social@Panther

--THIS CLEARS ALL PROFILES!!!
DELETE FROM PROFILE;

--INSERT USERS:
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (0, 'claude ortiz', 'claude.ortiz@example.com','outside', TO_DATE('1969-07-16 19:56:50', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (1, 'jaime gallego', 'jaime.gallego@example.com','warning', TO_DATE('1977-05-01 15:18:34', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (2, 'erna tukker', 'erna.tukker@example.com','buckeye', TO_DATE('1969-07-20 14:41:58', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (3, 'torben kramer', 'torben.kramer@example.com','mariposa', TO_DATE('1981-08-30 12:36:16', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (4, 'grace mckinney', 'grace.mckinney@example.com','slick', TO_DATE('1960-06-17 14:07:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (5, 'isabella miller', 'isabella.miller@example.com','1955', TO_DATE('1962-08-18 14:52:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (6, 'victor duval', 'victor.duval@example.com','dana', TO_DATE('1970-09-05 05:25:29', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (7, 'emilie andersen', 'emilie.andersen@example.com','goodgirl', TO_DATE('1972-12-22 02:49:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (8, 'lizelotte schinkel', 'lizelotte.schinkel@example.com','secrets', TO_DATE('1988-11-17 03:30:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (9, 'christian mortensen', 'christian.mortensen@example.com','edward1', TO_DATE('1993-04-06 22:10:08', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (10, 'cathriona lowe', 'cathriona.lowe@example.com','jammin', TO_DATE('1961-03-30 22:19:01', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (11, 'arzu bergmans', 'arzu.bergmans@example.com','duffy', TO_DATE('1955-06-28 01:25:09', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (12, 'timothe perez', 'timothe.perez@example.com','pianoman', TO_DATE('1989-11-19 16:23:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (13, 'sander madsen', 'sander.madsen@example.com','race', TO_DATE('1963-07-29 23:47:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (14, 'milla haapala', 'milla.haapala@example.com','sinbad', TO_DATE('1954-09-27 17:03:12', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (15, 'gabriella wagner', 'gabriella.wagner@example.com','marian', TO_DATE('1960-09-22 02:31:11', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (16, 'garance dufour', 'garance.dufour@example.com','noodle', TO_DATE('1971-06-29 22:05:41', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (17, 'selma kristensen', 'selma.kristensen@example.com','night', TO_DATE('1978-12-13 09:09:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (18, 'juho wirtanen', 'juho.wirtanen@example.com','jackson5', TO_DATE('1973-06-05 23:24:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (19, 'tomas perez', 'tomas.perez@example.com','heather', TO_DATE('1954-10-03 09:14:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (20, 'maria arias', 'maria.arias@example.com','asdfg', TO_DATE('1970-02-19 21:48:32', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (21, 'henrica verschuure', 'henrica.verschuure@example.com','tzpvaw', TO_DATE('1955-08-11 16:56:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (22, 'yann burgering', 'yann.burgering@example.com','lkjhgfds', TO_DATE('1977-08-29 21:32:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (23, 'bella robinson', 'bella.robinson@example.com','angelo', TO_DATE('1954-09-19 13:14:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (24, 'erwan fournier', 'erwan.fournier@example.com','masamune', TO_DATE('1954-04-19 16:23:02', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (25, 'emily lowe', 'emily.lowe@example.com','monkey', TO_DATE('1959-04-09 00:51:34', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (26, 'isabella coleman', 'isabella.coleman@example.com','emma', TO_DATE('1982-08-31 06:47:50', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (27, 'charles morin', 'charles.morin@example.com','mine', TO_DATE('1960-07-08 03:12:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (28, 'carl christensen', 'carl.christensen@example.com','chester1', TO_DATE('1987-09-17 04:56:42', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (29, 'topias polon', 'topias.polon@example.com','grover', TO_DATE('1961-02-13 14:08:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (30, 'noah colin', 'noah.colin@example.com','semper', TO_DATE('1988-03-16 04:18:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (31, 'fadma bentvelzen', 'fadma.bentvelzen@example.com','fields', TO_DATE('1980-10-03 15:14:40', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (32, 'karla andersen', 'karla.andersen@example.com','jimjim', TO_DATE('1995-05-23 10:37:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (33, 'frieda kaiser', 'frieda.kaiser@example.com','satan666', TO_DATE('1965-09-17 13:05:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (34, 'joseph hall', 'joseph.hall@example.com','doggies', TO_DATE('1979-06-06 01:09:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (35, 'sarah dumas', 'sarah.dumas@example.com','hammond', TO_DATE('1961-01-12 16:20:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (36, 'afşar başoğlu', 'afşar.başoğlu@example.com','rockstar', TO_DATE('1945-09-13 00:49:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (37, 'kent day', 'kent.day@example.com','stella', TO_DATE('1974-05-07 07:59:42', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (38, 'aria thompson', 'aria.thompson@example.com','nutmeg', TO_DATE('1956-05-13 15:36:05', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (39, 'jen brown', 'jen.brown@example.com','ziggy1', TO_DATE('1949-06-17 01:19:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (40, 'ebony bernadina', 'ebony.bernadina@example.com','republic', TO_DATE('1981-09-08 11:56:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (41, 'selma pedersen', 'selma.pedersen@example.com','merlin1', TO_DATE('1955-10-19 17:46:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (42, 'sophie matthews', 'sophie.matthews@example.com','zhuan', TO_DATE('1990-05-27 04:43:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (43, 'leanne pelletier', 'leanne.pelletier@example.com','puffin', TO_DATE('1951-12-11 16:22:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (44, 'carla mendez', 'carla.mendez@example.com','kkkkkkk', TO_DATE('1970-03-22 01:29:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (45, 'lorenzo garrido', 'lorenzo.garrido@example.com','nintendo', TO_DATE('1961-03-26 22:04:57', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (46, 'elísio da rosa', 'elísio.darosa@example.com','artemis', TO_DATE('1961-12-02 01:47:50', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (47, 'maya morel', 'maya.morel@example.com','shalom', TO_DATE('1974-09-06 11:38:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (48, 'marie moulin', 'marie.moulin@example.com','niners', TO_DATE('1954-05-20 15:23:58', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (49, 'sofie mortensen', 'sofie.mortensen@example.com','photoes', TO_DATE('1972-01-31 09:18:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (50, 'emily powell', 'emily.powell@example.com','welcome1', TO_DATE('1981-11-28 14:44:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (51, 'jocelyn bredius', 'jocelyn.bredius@example.com','gideon', TO_DATE('1989-06-11 08:50:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (52, 'mélody rolland', 'mélody.rolland@example.com','jjjjj', TO_DATE('1953-10-28 08:45:40', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (53, 'fernando reed', 'fernando.reed@example.com','balance', TO_DATE('1963-06-08 04:37:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (54, 'halit edwards', 'halit.edwards@example.com','cascade', TO_DATE('1961-01-23 18:19:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (55, 'florinda teixeira', 'florinda.teixeira@example.com','bigdog', TO_DATE('1956-07-05 20:30:42', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (56, 'elizabeth lewis', 'elizabeth.lewis@example.com','julie', TO_DATE('1955-04-08 17:58:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (57, 'debbie tucker', 'debbie.tucker@example.com','breanna', TO_DATE('1967-05-16 01:14:54', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (58, 'lonnie lowe', 'lonnie.lowe@example.com','hondas', TO_DATE('1956-09-30 23:40:15', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (59, 'martin ramirez', 'martin.ramirez@example.com','hewlett', TO_DATE('1992-08-10 22:54:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (60, 'louisa lopez', 'louisa.lopez@example.com','sunfire', TO_DATE('1972-09-20 19:09:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (61, 'coline michel', 'coline.michel@example.com','hall', TO_DATE('1992-05-04 10:15:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (62, 'barış kumcuoğlu', 'barış.kumcuoğlu@example.com','stylus', TO_DATE('1975-01-25 15:36:09', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (63, 'paige morrison', 'paige.morrison@example.com','chick', TO_DATE('1955-08-12 15:27:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (64, 'martin fontai', 'martin.fontai@example.com','bimbo', TO_DATE('1949-01-28 04:15:50', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (65, 'davina silveira', 'davina.silveira@example.com','training', TO_DATE('1978-09-09 04:58:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (66, 'elias perrin', 'elias.perrin@example.com','mojo', TO_DATE('1953-11-02 00:44:48', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (67, 'bianca otto', 'bianca.otto@example.com','allgood', TO_DATE('1951-09-03 02:33:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (68, 'elise wimmer', 'elise.wimmer@example.com','seadoo', TO_DATE('1961-10-12 05:25:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (69, 'bradly schenkeveld', 'bradly.schenkeveld@example.com','natasha', TO_DATE('1974-10-15 14:28:01', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (70, 'vedat topçuoğlu', 'vedat.topçuoğlu@example.com','mirror', TO_DATE('1992-11-17 14:57:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (71, 'carrie woods', 'carrie.woods@example.com','switch', TO_DATE('1992-02-26 04:50:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (72, 'lance riley', 'lance.riley@example.com','devon', TO_DATE('1967-06-30 06:28:14', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (73, 'milagros carrasco', 'milagros.carrasco@example.com','rainbow1', TO_DATE('1966-04-01 13:31:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (74, 'sancho teixeira', 'sancho.teixeira@example.com','magic32', TO_DATE('1962-04-14 14:28:51', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (75, 'gavin adams', 'gavin.adams@example.com','000000', TO_DATE('1969-06-09 02:03:12', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (76, 'jacey kronenburg', 'jacey.kronenburg@example.com','clancy', TO_DATE('1971-08-06 23:35:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (77, 'isobel smith', 'isobel.smith@example.com','jackal', TO_DATE('1978-03-19 03:11:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (78, 'noëmi van roij', 'noëmi.vanroij@example.com','franks', TO_DATE('1977-06-25 00:48:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (79, 'borja crespo', 'borja.crespo@example.com','think', TO_DATE('1956-11-03 03:03:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (80, 'cléa richard', 'cléa.richard@example.com','llllllll', TO_DATE('1994-02-22 23:04:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (81, 'jerome olson', 'jerome.olson@example.com','comedy', TO_DATE('1975-04-04 05:32:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (82, 'núrio santos', 'núrio.santos@example.com','420000', TO_DATE('1986-04-12 17:06:51', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (83, 'maëlia simon', 'maëlia.simon@example.com','video', TO_DATE('1979-12-11 10:02:34', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (84, 'kaya alnıaçık', 'kaya.alnıaçık@example.com','stealth', TO_DATE('1964-03-06 03:23:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (85, 'blake smith', 'blake.smith@example.com','virtual', TO_DATE('1946-08-20 21:10:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (86, 'david moulin', 'david.moulin@example.com','username', TO_DATE('1984-03-03 08:18:12', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (87, 'charlotte grewal', 'charlotte.grewal@example.com','johngalt', TO_DATE('1964-12-30 16:31:26', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (88, 'juan craig', 'juan.craig@example.com','1972', TO_DATE('1987-08-16 22:23:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (89, 'auguste olivier', 'auguste.olivier@example.com','boozer', TO_DATE('1993-08-19 12:44:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (90, 'cengizhan rodermond', 'cengizhan.rodermond@example.com','bluedog', TO_DATE('1987-02-21 19:45:28', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (91, 'lya guerin', 'lya.guerin@example.com','recovery', TO_DATE('1946-12-31 02:14:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (92, 'ariane gauthier', 'ariane.gauthier@example.com','gunther', TO_DATE('1957-10-23 11:46:30', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (93, 'dwayne matthews', 'dwayne.matthews@example.com','litle', TO_DATE('1978-03-08 01:38:14', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (94, 'eli white', 'eli.white@example.com','dakota1', TO_DATE('1959-03-25 10:20:50', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (95, 'eléa girard', 'eléa.girard@example.com','baseball', TO_DATE('1962-06-22 11:39:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (96, 'herminia herrera', 'herminia.herrera@example.com','sword', TO_DATE('1962-05-07 11:12:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (97, 'isaac martin', 'isaac.martin@example.com','womam', TO_DATE('1953-03-29 05:31:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (98, 'fatma ekici', 'fatma.ekici@example.com','maserati', TO_DATE('1954-08-31 11:09:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (99, 'kim chavez', 'kim.chavez@example.com','creative', TO_DATE('1976-06-18 16:59:41', 'YYYY-MM-DD HH24:MI:SS'));
